#ifndef OPENSIM_OSIMMOCOPROJECTEDMARGINOFSTABILITYGOALDLL_H
#define OPENSIM_OSIMMOCOPROJECTEDMARGINOFSTABILITYGOALDLL_H

#ifndef _WIN32
    #define OSIMMOCOPROJECTEDMARGINOFSTABILITYGOAL_API
#else
    #ifdef OSIMMOCOPROJECTEDMARGINOFSTABILITYGOAL_EXPORTS
        #define OSIMMOCOPROJECTEDMARGINOFSTABILITYGOAL_API __declspec(dllexport)
    #else
        #define OSIMMOCOPROJECTEDMARGINOFSTABILITYGOAL_API __declspec(dllimport)
    #endif
#endif

#endif // OPENSIM_OSIMMOCOPROJECTEDMARGINOFSTABILITYGOALDLL_H
