#ifndef OPENSIM_OSIMMOCOWEIGHTEDMARGINOFSTABILITYGOALDLL_H
#define OPENSIM_OSIMMOCOWEIGHTEDMARGINOFSTABILITYGOALDLL_H

#ifndef _WIN32
    #define OSIMMOCOWEIGHTEDMARGINOFSTABILITYGOAL_API
#else
    #ifdef OSIMMOCOWEIGHTEDMARGINOFSTABILITYGOAL_EXPORTS
        #define OSIMMOCOWEIGHTEDMARGINOFSTABILITYGOAL_API __declspec(dllexport)
    #else
        #define OSIMMOCOWEIGHTEDMARGINOFSTABILITYGOAL_API __declspec(dllimport)
    #endif
#endif

#endif // OPENSIM_OSIMMOCOWEIGHTEDMARGINOFSTABILITYGOALDLL_H
