lumbar_weights = [0.0001, 0.0001, 0.0001, 0.000001, 0.0001, 0.0001];
lumbar_results = [0.020797, 0.020996, 0, 0.000212, 0, 0];
stability_weights = [1, 1, 1, 1, 0.001, 1];
stability_results = [0.051847, 0.053271, 0, 0.048020, 0, 0];

lumbar = lumbar_results./lumbar_weights;
stability = stability_results./stability_weights;
createfigure([1, 4, 7, 10, 13, 16], lumbar, [2, 5, 8, 11, 14, 17], stability);

xlim([-0.5, 18.5]);

% The following is a MATLAB auto-generated function based on a saved plot.
function createfigure(xvector1, yvector1, xvector2, yvector2)
%CREATEFIGURE(xvector1, yvector1, xvector2, yvector2)
%  XVECTOR1:  bar xvector
%  YVECTOR1:  bar yvector
%  XVECTOR2:  bar xvector
%  YVECTOR2:  bar yvector

%  Auto-generated by MATLAB on 04-Nov-2022 15:35:26

% Create figure
figure;

% Create axes
axes1 = axes;
hold(axes1,'on');
colororder([0.85 0.325 0.098]);

% Activate the left side of the axes
yyaxis(axes1,'left');
% Create bar
bar(xvector1,yvector1,'DisplayName','Lumbar',...
    'FaceColor',[0.313725490196078 0.564705882352941 0.729411764705882],...
    'EdgeColor','none',...
    'BarWidth',0.3);

% Create ylabel
ylabel('Lumbar Loading');

% Set the remaining axes properties
set(axes1,'YColor',[0.149019607843137 0.149019607843137 0.149019607843137]);
% Activate the right side of the axes
yyaxis(axes1,'right');
% Create bar
bar(xvector2,yvector2,'DisplayName','Stability',...
    'FaceColor',[0.909803921568627 0.529411764705882 0.364705882352941],...
    'EdgeColor','none',...
    'BarWidth',0.3);

% Create ylabel
ylabel('Stability','Rotation',270);

% Set the remaining axes properties
set(axes1,'YColor',[0.149019607843137 0.149019607843137 0.149019607843137]);
% Create xlabel
xlabel({'Simulation Case',''});

% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[-0.5 15.5]);
box(axes1,'on');
hold(axes1,'off');
% Set the remaining axes properties
set(axes1,'FontSize',20,'OuterPosition',[0 0 0.95 1],'XTick',[1.5 4.5 7.5 10.5 13.5 16.5],'XTickLabel',...
    {'1','2','3','4','5', '6'});
% Create legend
legend1 = legend(axes1,'show');
set(legend1,'Position',[0.144362358447775 0.779761904761919 0.134738186462324 0.113095238095238]);
end
