%lumbar_weights = [0.0001, 0.0001, 0.0001, 0.0001];
%lumbar_results = [0.009094, 0.005961, 0.010269, 0.005317];
%stability_weights = [1, 1, 1, 1];
%stability_results = [0.046672, 0.047072, 0.050387, 0.045132];

root = '/Users/daniel/Documents/GitHub/ergonomics/Scripts/20_NewModel/results/'

files = {'normal.sto', 'weak.sto', 'stability.sto', 'lumbar.sto', 'combined.sto', 'combined_ankle.sto'};
lumbar_weights = [0.0001, 0.0001, 0.000001, 0.0001, 0.0001, 0.0001];
stability_weights = [1, 1, 1, 0.01, 1, 1];

lumbar_matrix = [];
stability_matrix = []

for results = 0
    subroot = [root num2str(results)];
    lumbar_results = [];
    stability_results = [];
    for i = 1:length(files)
        data_file = Data([subroot filesep files{i}]);
        lumbar_results = [lumbar_results getLumbarCost(data_file)];
        stability_results = [stability_results getStabilityCost(data_file)];
    end
    lumbar_matrix = [lumbar_matrix; lumbar_results];
    stability_matrix = [stability_matrix; stability_results];
end

lumbar_mean = mean(lumbar_matrix, 1);
lumbar_sdev = std(lumbar_matrix, 1);
stability_mean = mean(stability_matrix, 1);
stability_sdev = std(stability_matrix, 1);

lumbar_results = lumbar_mean;
stability_results = stability_mean;

n_results = length(lumbar_weights);
lumbar = lumbar_results./lumbar_weights;
stability = stability_results./stability_weights;
tick_locs = 1:3:(n_results-1)*3 + 1;


xlim([tick_locs(1) - 1.5, tick_locs(end) + 1.5]);

mid_ticks = (tick_locs + tick_locs + 1)/2;
labels = cell(n_results, 1);
for i = 1:n_results
    labels{i} = num2str(i);
end

createfigure(tick_locs, lumbar, tick_locs + 1, stability, mid_ticks, labels, lumbar_sdev./lumbar_weights, stability_sdev./stability_weights);

% The following is a MATLAB auto-generated function based on a saved plot.
function createfigure(xvector1, yvector1, xvector2, yvector2, mid_ticks, labels, err1, err2)
%CREATEFIGURE(xvector1, yvector1, xvector2, yvector2)
%  XVECTOR1:  bar xvector
%  YVECTOR1:  bar yvector
%  XVECTOR2:  bar xvector
%  YVECTOR2:  bar yvector

%  Auto-generated by MATLAB on 04-Nov-2022 15:35:26

% Create figure
figure;

% Create axes
axes1 = axes;
hold(axes1,'on');
colororder([0.85 0.325 0.098]);

% Activate the left side of the axes
yyaxis(axes1,'left');
% Create bar
bar(xvector1,yvector1,'DisplayName','Lumbar',...
    'FaceColor',[0.313725490196078 0.564705882352941 0.729411764705882],...
    'EdgeColor','none',...
    'BarWidth',0.3);
er = errorbar(xvector1, yvector1, err1);
er.Color = 0.7*[0.313725490196078 0.564705882352941 0.729411764705882];
er.LineStyle = 'none';
er.LineWidth = 1.2;
er.HandleVisibility = 'off';

% Create ylabel
ylabel('Lumbar Loading');

% Set the remaining axes properties
set(axes1,'YColor',[0.149019607843137 0.149019607843137 0.149019607843137]);
% Activate the right side of the axes
yyaxis(axes1,'right');
% Create bar
bar(xvector2,yvector2,'DisplayName','Stability',...
    'FaceColor',[0.909803921568627 0.529411764705882 0.364705882352941],...
    'EdgeColor','none',...
    'BarWidth',0.3);
er = errorbar(xvector2, yvector2, err2);
er.Color = 0.7*[0.909803921568627 0.529411764705882 0.364705882352941];
er.LineStyle = 'none';
er.LineWidth = 1.2;
er.HandleVisibility = 'off';

% Create ylabel
ylabel('Stability','Rotation',270);

% Set the remaining axes properties
set(axes1,'YColor',[0.149019607843137 0.149019607843137 0.149019607843137]);
% Create xlabel
xlabel({'Simulation Case',''});

% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[-0.5 15.5]);
box(axes1,'on');
hold(axes1,'off');
% Set the remaining axes properties
set(axes1,'FontSize',20,'OuterPosition',[0 0 0.95 1],'XTick',mid_ticks,'XTickLabel',labels);
% Create legend
legend1 = legend(axes1,'show');
set(legend1,'Position',[0.144362358447775 0.779761904761919 0.134738186462324 0.113095238095238]);
end

function cost = getStabilityCost(data_file)
    fields = strsplit(data_file.Header{11}, '=');
    cost = str2double(fields{2});
end

function cost = getLumbarCost(data_file)
    fields = strsplit(data_file.Header{10}, '=');
    cost = str2double(fields{2});
end
